# woohoo, yaml engineering
name: Build/deploy Lambda

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: centos:7
    # amazonlinux's gexiv2 package is broken as of december 2019!!
    # and the official rust builds from rustup have a weird build error on older distros (glibcs?)
    steps:
    - run: yum install -y epel-release && yum install -y git gcc binutils clang cmake3 make zip rust cargo libgexiv2-devel
    - run: ln -s cmake3 /usr/bin/cmake
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: imgroll-cargo-registry
    - uses: actions/cache@v1
      with:
        path: target
        key: imgroll-cargo-target
    - run: cargo build --verbose --release --bin imgroll-lambda
    - run: ldd -v target/release/imgroll-lambda
    - run: mkdir -p lambda/lib && cp target/release/imgroll-lambda lambda/bootstrap && cp /usr/lib*/*exiv2*so.* /usr/lib*/libgobject*so.* /usr/lib*/libglib*so.* /usr/lib*/libgio*so.* lambda/lib/
    - run: (cd lambda && zip -y -r ../lambda.zip *)
    - uses: stcalica/update-lambda@0.0.2
      with:
        package: lambda.zip
        function-name: ${{ secrets.FUNCTION_NAME }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # the IAM user for this only needs lambda:UpdateFunctionCode on this function
